[package]
name = "rusty-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.59"    # error handling
itertools = "0.10.3" # useful iterator extensions
thiserror = "1.0.32" # error handling
ptree = "0.4.0"

sqlparser = "0.38.0"
