[package]
name = "sqlite"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.59"    # error handling
itertools = "0.10.3" # useful iterator extensions
thiserror = "1.0.32" # error handling
prettytable-rs = "^0.10"
sqlparser = "0.38.0"
